[package]
name = "rust-async"
version = "0.1.0"
authors = ["Jesse Lucas <jesse@jesselucas.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.18", features = ["full"] }
futures = "0.3.4"
